### ISSUE TITLE
Cloud Build always failing

### ISSUE THREAD

**Issue by MeneghettiFlux** [adjust/unity_sdk#106]
Hello! I integrated Adjust on a project and build with success for Android, but I'm having issues with the iOS version. We use cloud build with these configurations:

Unity 3.5.3p8;
XCode 7.2.1 (Tried 7.3.1, same problem);
Adjust 4.11.3;

Changing the Unity Version or XCode version does not change the problem.

I've seen the other tickets here with similar problems and tried the solutions with no success.

Below is the related excerpt of the Full Log from Cloud Build.

```
25092:        [xcode]     cd /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2
25093:        [xcode]     export IPHONEOS_DEPLOYMENT_TARGET=8.4
25094:        [xcode]     export PATH="/APPLICATION_PATH/Xcode7_2_1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/APPLICATION_PATH/Xcode7_2_1.app/Contents/Developer/usr/bin:/APPLICATION_PATH/Android Studio.app/sdk:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/BUILD_PATH/.mason/buildpacks/unity/libs/vendor/jsawk:/BUILD_PATH/.mason/buildpacks/xcode/libs/vendor/jsawk:/BUILD_PATH/.rvm/bin"
25095:        [xcode]     /APPLICATION_PATH/Xcode7_2_1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch armv7 -isysroot /APPLICATION_PATH/Xcode7_2_1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Release-iphoneos -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2 -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Plugins/iOS/SeedsSDK -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Adjust/iOS -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Plugins/iOS -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Plugins/iOS/Fabric/Crashlytics-Wrapper -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Plugins/iOS/Fabric/Fabric-Init -F/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Release-iphoneos -F/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Frameworks/Plugins/iOS/Fabric -F/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Frameworks/FacebookSDK/Plugins/iOS -F/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/UnityAds -filelist /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/trenga.LinkFileList -Xlinker -map -Xlinker /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/trenga-LinkMap-normal-armv7.txt -miphoneos-version-min=8.4 -dead_strip -weak_framework CoreMotion -weak-lSystem -ObjC -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -weak_framework iAd -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lSeedsLibrary -framework Crashlytics /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Adjust/iOS/AdjustSdk.a -lChartboost -framework FBSDKShareKit -lGameAnalytics -framework Bolts -framework FBSDKLoginKit -framework FBSDKCoreKit -framework Fabric -framework ParseFacebookUtilsV4 -framework Parse -lCrashlyticsiOSWrapper -lFabriciOSInit -framework StoreKit -framework GameKit -weak_framework AdSupport -lsqlite3 -lz -framework UnityAds -framework CoreTelephony -framework Security -lc++ -framework CoreData -Xlinker -dependency_info -Xlinker /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/trenga_dependency_info.dat -o /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/trenga
25096:        [xcode] Undefined symbols for architecture armv7:
25097:        [xcode]   "_kSecAttrAccessGroupToken", referenced from:
25098:        [xcode]       -[ADJActivityState assignUuid:] in AdjustSdk.a(ADJActivityState.o)
25099:        [xcode]       -[ADJKeychain setValue:forKeychainKey:inService:] in AdjustSdk.a(ADJKeychain.o)
25100:        [xcode]       -[ADJKeychain keychainItemForKeyNew:service:] in AdjustSdk.a(ADJKeychain.o)
25101:        [xcode]       -[ADJKeychain setValueWithStatus:forKeychainKey:inService:] in AdjustSdk.a(ADJKeychain.o)
25102:        [xcode]       -[ADJKeychain wasWritingSuccessful:forKeychainKey:inService:] in AdjustSdk.a(ADJKeychain.o)
25103:        [xcode] ld: symbol(s) not found for architecture armv7
25104:        [xcode] clang: error: linker command failed with exit code 1 (use -v to see invocation)
25105:        [xcode] Ld build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/trenga normal arm64
25106:        [xcode]     cd /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2
25107:        [xcode]     export IPHONEOS_DEPLOYMENT_TARGET=8.4
25108:        [xcode]     export PATH="/APPLICATION_PATH/Xcode7_2_1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/APPLICATION_PATH/Xcode7_2_1.app/Contents/Developer/usr/bin:/APPLICATION_PATH/Android Studio.app/sdk:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/BUILD_PATH/.mason/buildpacks/unity/libs/vendor/jsawk:/BUILD_PATH/.mason/buildpacks/xcode/libs/vendor/jsawk:/BUILD_PATH/.rvm/bin"
25109:        [xcode]     /APPLICATION_PATH/Xcode7_2_1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /APPLICATION_PATH/Xcode7_2_1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Release-iphoneos -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2 -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Plugins/iOS/SeedsSDK -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Adjust/iOS -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Plugins/iOS -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Plugins/iOS/Fabric/Crashlytics-Wrapper -L/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Plugins/iOS/Fabric/Fabric-Init -F/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Release-iphoneos -F/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Frameworks/Plugins/iOS/Fabric -F/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Frameworks/FacebookSDK/Plugins/iOS -F/BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/UnityAds -filelist /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/trenga.LinkFileList -Xlinker -map -Xlinker /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/trenga-LinkMap-normal-arm64.txt -miphoneos-version-min=8.4 -dead_strip -weak_framework CoreMotion -weak-lSystem -ObjC -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -weak_framework iAd -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lSeedsLibrary -framework Crashlytics /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/Adjust/iOS/AdjustSdk.a -lChartboost -framework FBSDKShareKit -lGameAnalytics -framework Bolts -framework FBSDKLoginKit -framework FBSDKCoreKit -framework Fabric -framework ParseFacebookUtilsV4 -framework Parse -lCrashlyticsiOSWrapper -lFabriciOSInit -framework StoreKit -framework GameKit -weak_framework AdSupport -lsqlite3 -lz -framework UnityAds -framework CoreTelephony -framework Security -lc++ -framework CoreData -Xlinker -dependency_info -Xlinker /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/trenga_dependency_info.dat -o /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/trenga
25110:        [xcode] ld: warning: arm64 function not 4-byte aligned: ltmp0 from /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
25111:        [xcode] ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.58qkB2/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
25112:        [xcode] ** BUILD FAILED **
25113:        [xcode] The following build commands failed:
25114:        [xcode] 	Ld build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/trenga normal armv7
25115:        [xcode] (1 failure)
25116: ! build of 'ios-release-new-xcode' failed. compile failed
25117: Publishing build 6 of flux-game-studio/trenga for target 'ios-release-new-xcode'...
25118: Uploading extra_data/artifacts/icon.png  ...done
25119: publishing finished successfully.
25120: uninstalling iOS credentials for flux-game-studio/trenga - ios-release-new-xcode
25121: MAC verified OK
25122: Removing certificate...
25123:   removing: /BUILD_PATH/Library/MobileDevice/Provisioning Profiles/8ebf8f9a-c983-4144-9aa9-2ba69181146a.mobileprovision
25124: Storing CACHE_PATH to cache key library_5_3_8f1
25125: done.
25126: Build step 'Execute shell' marked build as failure
25127: postbuildstatus finished successfully.
25128: Finished: FAILURE
```

**Comment by uerceg** [comment]
You should try using Xcode 8.

**Comment by MeneghettiFlux** [comment]
Thanks! I think that when I tried to use Xcode 8.3 it said it was not compatible, now I will try with 8.0 as it showed no incompatibility warning. Thanks!

**Comment by MeneghettiFlux** [comment]
Unfortunately with both 8.0 and 8.3, it gives this error:

"24051:        [xcode] xcodebuild: error: Unable to read project 'Unity-iPhone.xcodeproj'."

```
 + Building with Xcode 8.3.2
24035:        args: -sdk iphoneos PROVISIONING_PROFILE=8ebf8f9a-c983-4144-9aa9-2ba69181146a DEVELOPMENT_TEAM=VF8TW22896 CODE_SIGN_IDENTITY=iPhone Distribution: Leela Games Ltda (VF8TW22896) -xcconfig /BUILD_PATH/.mason/buildpacks/xcode/bin/../libs/dSYM-Config.xcconfig -scheme Unity-iPhone -archivePath /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.Gkr6Dy/build.xcarchive archive
24036:        [xcode] Now using system ruby.
24037:        [xcode] User defaults from command line:
24038:        [xcode]     IDEArchivePathOverride = /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.Gkr6Dy/build.xcarchive
24039:        [xcode] Build settings from command line:
24040:        [xcode]     CODE_SIGN_IDENTITY = iPhone Distribution: Leela Games Ltda (VF8TW22896)
24041:        [xcode]     DEVELOPMENT_TEAM = VF8TW22896
24042:        [xcode]     PROVISIONING_PROFILE = 8ebf8f9a-c983-4144-9aa9-2ba69181146a
24043:        [xcode]     SDKROOT = iphoneos10.3
24044:        [xcode] Build settings from configuration file '/BUILD_PATH/.mason/buildpacks/xcode/bin/../libs/dSYM-Config.xcconfig':
24045:        [xcode]     DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
24046:        [xcode]     DEPLOYMENT_POSTPROCESSING = YES
24047:        [xcode]     GCC_GENERATE_DEBUGGING_SYMBOLS = YES
24048:        [xcode]     SEPARATE_STRIP = YES
24049:        [xcode]     STRIP_INSTALLED_PRODUCT = YES
24050:        [xcode] 2017-06-23 14:14:22.389 xcodebuild[3924:17838] Error Domain=NSCocoaErrorDomain Code=3840 "Close tag on line 1 does not match open tag key" UserInfo={NSDebugDescription=Close tag on line 1 does not match open tag key, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Malformed data byte group at line 1; invalid hex" UserInfo={NSDebugDescription=Malformed data byte group at line 1; invalid hex}}
24051:        [xcode] xcodebuild: error: Unable to read project 'Unity-iPhone.xcodeproj'.
24052:        [xcode] 	Reason: Project /BUILD_PATH/flux-game-studio.trenga.ios-release-new-xcode/Project/temp.Gkr6Dy/Unity-iPhone.xcodeproj cannot be opened because the project file cannot be parsed.
24053: ! build of 'ios-release-new-xcode' failed. compile failed
24054: Publishing build 10 of flux-game-studio/trenga for target 'ios-release-new-xcode'...
24055: Uploading extra_data/artifacts/icon.png  ...done
24056: publishing finished successfully.
24057: uninstalling iOS credentials for flux-game-studio/trenga - ios-release-new-xcode
24058: MAC verified OK
24059: Removing certificate...
24060:   removing: /BUILD_PATH/Library/MobileDevice/Provisioning Profiles/8ebf8f9a-c983-4144-9aa9-2ba69181146a.mobileprovision
24061: Storing CACHE_PATH to cache key library_5_3_8f1
24062: done.
24063: Build step 'Execute shell' marked build as failure
24064: postbuildstatus finished successfully.
24065: Finished: FAILURE
```

**Comment by MeneghettiFlux** [comment]
Also, when building from XCode, This error occurs:

```
Undefined symbols for architecture armv7:
  "_kSecAttrAccessGroupToken", referenced from:
      -[ADJActivityState assignUuid:] in AdjustSdk.a(ADJActivityState.o)
      -[ADJKeychain setValue:forKeychainKey:inService:] in AdjustSdk.a(ADJKeychain.o)
      -[ADJKeychain keychainItemForKeyNew:service:] in AdjustSdk.a(ADJKeychain.o)
      -[ADJKeychain setValueWithStatus:forKeychainKey:inService:] in AdjustSdk.a(ADJKeychain.o)
      -[ADJKeychain wasWritingSuccessful:forKeychainKey:inService:] in AdjustSdk.a(ADJKeychain.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by uerceg** [comment]
Hi @MeneghettiFlux 

Can you try using latest Unity SDK v4.11.4 (https://github.com/adjust/unity_sdk/releases/tag/v4.11.4) and let us know if these issues were solved with that update.

Thanks in advance for your answer.

Cheers

**Comment by uerceg** [comment]
Hi @meneghettiflux

Any update on this one?

Cheers.

**Comment by MeneghettiFlux** [comment]
Hey @uerceg 

Unfortunatly I can't give you precise informations, as I have moved between 3~4 projects since the last message here (september 28) and I can't recall the details of what we had done at the time, but the short version would be: "It didn't work".

All I remember was that we didn't solve the Cloud Build settings, and I had to change a lot of files just to be able to build from a Mac machine (I sincerily don't know which files being modified did the trick).

I don't think we will work on this project in the near future, so I can't make tests or spend too much time going after all the infos missing above. If you feel the need to close this Issue, that's not a problem to us. But we haven't solved it completely. 

Thanks for the help!

**Comment by uerceg** [comment]
Yeah, we have addressed specifically issue mentioned in your comment in here (https://github.com/adjust/unity_sdk/issues/106#issuecomment-311423453) in this latest version so I think that this error should not pop up anymore with latest SDK version. I will close this issue with that in mind, but in case you ever go back to this topic and encounter same issue, feel free to reopen the issue and we'll take a look again.

Cheers!
